// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgxfdplrlvrsucfkvjmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNneGZkcGxybHZyc3VjZmt2am1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyODUyOTMsImV4cCI6MjA1NTg2MTI5M30.YE64gYHtCifJ3rCEXlgHQwAWLgnkxQOHDgT6-NHFtqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);